/* eslint-disable n8n-nodes-base/node-filename-against-convention */
import type { INodeTypeDescription } from 'n8n-workflow';
import { NodeConnectionTypes } from 'n8n-workflow';

export const nodeDescription: INodeTypeDescription = {
	displayName: 'PayByPhone',
	name: 'paybyphone',
	icon: { light: 'file:logo.svg', dark: 'file:logo.black.svg' },
	group: ['input'],
	version: [1],
	description: 'PayByPhone Node',
	defaults: {
		name: 'PayByPhone',
	},
	inputs: [NodeConnectionTypes.Main],
	outputs: [NodeConnectionTypes.Main],
	usableAsTool: true,
	credentials: [
		{
			name: 'PayByPhoneApi',
			required: true,
		},
	],
	properties: [
		{
			displayName: 'Resource',
			name: 'resource',
			type: 'options',
			options: [
				{ name: 'Location', value: 'location' },
				{ name: 'Parking Session', value: 'parkingSession' },
				{ name: 'Payment Method', value: 'paymentMethod' },
				{ name: 'Quote', value: 'quote' },
				{ name: 'Rate', value: 'rate' },
				{ name: 'Vehicle', value: 'vehicle' },
			],
			default: 'vehicle',
			noDataExpression: true,
			required: true,
			description: 'Resource type to operate on',
		},
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['parkingSession'] } },
			options: [
				{
					name: 'List',
					value: 'list',
					description: 'List parking sessions',
					action: 'List parking sessions',
				},
				{
					name: 'Start',
					value: 'start',
					description: 'Start a parking session',
					action: 'Start a parking session',
				},
			],
			default: 'list',
			noDataExpression: true,
		},
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['vehicle'] } },
			options: [
				{
					name: 'List',
					value: 'list',
					description: 'List vehicles',
					action: 'List vehicles',
				},
			],
			default: 'list',
			noDataExpression: true,
		},
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['location'] } },
			options: [
				{
					name: 'List',
					value: 'list',
					description: 'List locations',
					action: 'List locations',
				},
			],
			default: 'list',
			noDataExpression: true,
		},
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['paymentMethod'] } },
			options: [
				{
					name: 'List',
					value: 'list',
					description: 'List payment methods',
					action: 'List payment methods',
				},
			],
			default: 'list',
			noDataExpression: true,
		},
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['rate'] } },
			options: [
				{
					name: 'Get',
					value: 'get',
					description: 'Get rate options',
					action: 'Get rate options',
				},
			],
			default: 'get',
			noDataExpression: true,
		},
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			displayOptions: { show: { resource: ['quote'] } },
			options: [
				{
					name: 'Get',
					value: 'get',
					description: 'Get quote',
					action: 'Get quote',
				},
			],
			default: 'get',
			noDataExpression: true,
		},
		{
			displayName: 'Quote ID',
			name: 'quoteId',
			type: 'string',
			required: true,
			displayOptions: { show: { operation: ['start'], resource: ['parkingSession'] } },
			default: '',
			placeholder: 'Quote ID',
		},
		{
			displayName: 'Payment Account ID',
			name: 'paymentAccountId',
			type: 'string',
			required: true,
			displayOptions: { show: { operation: ['start'], resource: ['parkingSession'] } },
			default: '',
			placeholder: 'Payment Account ID',
		},
		{
			displayName: 'License Plate',
			name: 'licensePlate',
			type: 'string',
			required: true,
			displayOptions: { show: { operation: ['get'], resource: ['rate', 'quote'] } },
			default: '',
			placeholder: 'License Plate',
		},
		{
			displayName: 'LocationId',
			name: 'locationId',
			type: 'string',
			required: true,
			displayOptions: { show: { operation: ['get'], resource: ['rate', 'quote'] } },
			default: '',
			placeholder: 'Location ID',
			description: 'Location ID',
		},
		{
			displayName: 'Rate Policy ID',
			name: 'ratePolicyId',
			type: 'string',
			required: true,
			displayOptions: { show: { operation: ['get'], resource: ['quote'] } },
			default: '',
			placeholder: 'Rate Policy ID',
		},
		{
			displayName: 'Number of Time Units',
			name: 'timeUnits',
			type: 'number',
			required: true,
			displayOptions: { show: { operation: ['get'], resource: ['quote'] } },
			default: '',
			placeholder: 'Number of time units',
		},
		{
			displayName: 'Time Units',
			name: 'timeUnit',
			type: 'options',
			required: true,
			displayOptions: { show: { operation: ['get'], resource: ['quote'] } },
			options: [
				{ name: 'Days', value: 'Days', action: 'Select days' },
				{ name: 'Minutes', value: 'Minutes', action: 'Select minutes' },
			],
			default: 'Days',
			placeholder: 'Time unit',
			description: 'Time unit',
		},
		{
			displayName: 'Location',
			name: 'location',
			type: 'string',
			required: true,
			displayOptions: { show: { operation: ['list'], resource: ['location'] } },
			default: '',
			placeholder: 'Search by location number',
		},
		{
			displayName: 'Additional Fields',
			name: 'additionalFields',
			type: 'collection',
			placeholder: 'Add Field',
			default: {},
			displayOptions: { show: { resource: ['parkingSession'], operation: ['list'] } },
			options: [
				{
					displayName: 'Include Past Sessions',
					name: 'includePastSessions',
					type: 'boolean',
					default: false,
				},
			],
		},
		{
			displayName: 'Additional Fields',
			name: 'additionalFields',
			type: 'collection',
			placeholder: 'Add Field',
			default: {},
			displayOptions: { show: { resource: ['vehicle'], operation: ['list'] } },
			options: [
				{
					displayName: 'Include Archived',
					name: 'includeArchived',
					type: 'boolean',
					default: false,
				},
			],
		},
	],
};
